version: '3.9'

services:
  nuxt:
    build: .
    container_name: fastcmsadmin
    restart: always
    networks: 
      - pn 
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    command: 
      "npm run start"
networks:
  pn:
    external: 
      name: private-network