version: '3.9'

services:
  vue3:
    build: .
    container_name: fastcmsadmin
    restart: always
    networks: 
      - pn 
    environment:
      NODE_ENV: production
      VUE_APP_API: https://a.fastcms.ir
      VUE_APP_VER: api/v1
    ports:
      - 8080:8080
networks:
  pn:
    external: 
      name: private-network